name: Build Mod

on: [push, pull_request, workflow_call]

jobs:
  buildJar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PATH
        run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew deploy

      - name: Upload built jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} Pull Request
          path: build/libs/${{ github.event.repository.name }}.jar